---
 path_markdown:
 path_header:
 path_catalog:
 path_repo:
 path_storage:
 path_log:
 path_tmp:
 modules:
 freva_url:
 contacts_url:
 email:
 project:
 account:
 partition:
 add_method: copy
 clean_tmp: True
 mem: 128
 time: 08:00:00
 nodelist: None
 nthreads: 0
 max_threads: 64
