---
 path_registry: /work/bk1318/test-data-repo/Shared_Data.md
 path_repo: /work/bk1318/test-data-repo
 project: clint
 account: bk1318
 mem: 128
 time: 08:00:00
 nodelist: None
 partition: compute
 nthreads: 0
 max_threads: 64
