---
 path_registry: /work/bk1318/Data_Repository/Shared_Data.md
 path_crawl: /work/bm1159/XCES/xces-work/data/crawl_my_data/user-
 account: bk1318
 mem: 128
 time: 08:00:00
 nodelist: None
 partition: compute
 nthreads: 0
 max_threads: 64
